import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NextUIProvider } from "@nextui-org/react";
import NavbarLayout from "@/components/layouts/Navbar";
import ReactQueryWrapper from "@/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mining Mine Bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryWrapper>
          <NextUIProvider>
            <NavbarLayout />
            {children}
          </NextUIProvider>
        </ReactQueryWrapper>
      </body>
    </html>
  );
}
